### ISSUE TITLE
Upsert returns 500/502/504 if given too many rows/characters ~2000 trips it

### ISSUE THREAD

**Issue by ShantanuNair** [supabase/vecs#27]
**Describe the bug**
> upsert returns 500/502/504 if given too many rows/characters ~2000 trips it

https://github.com/hwchase17/langchainjs/blob/6a40c13c52c6efe70a44070f31b458abc26876a8/langchain/src/vectorstores/supabase.ts#L74

I want to know if this is still an issue. If we are to use supabase for storing embeddings, I need to know that it can handle ~500 token chunks, for our use case. Counting characters is a no go, as I support multiple languages and tokenizers have varying character:token ratios depending on the language.

**Expected behavior**
Chunks of any reasonable size work well with upserts/inserts

**Screenshots**
https://github.com/hwchase17/langchainjs/blob/6a40c13c52c6efe70a44070f31b458abc26876a8/langchain/src/vectorstores/supabase.ts#L74

@olirice Appreciate any support :)

**Additional context**
Unsure if this is the right repo to discuss this but since it seems like pgvector-related work is happening here, thought this would be the right place to ask - if not let me know where would be better and I'll repost the issue there.

**Comment by olirice** [comment]
This question doesn't appear to be related to supabase/vecs. It would be better to ask in langchainjs and tag authors of the relevant commit

---

However, the 500 in your link is related to rows rather than tokens. It's implementing row chunking and isn't something the user needs to be aware of.

Postgres text columns can store up to 1 GB of text so you won't have any problems with a maximum number of characters

Also, the comment the explaining the problem that the addition of chunking resolves, not a current problem.
https://github.com/hwchase17/langchainjs/commit/3d0d5828cabf9bb158e30798c8ec0945b88f3e5d

so as long as you're running the latest version you should be good to go
