### ISSUE TITLE
Explain Query Method 

### ISSUE THREAD

**Issue by sri-oli** [supabase/vecs#65]
I would like to be able to explain query method to ensure that the query is actually leveraging the indices. 

```
collection.explain(<query params>)
```

**Comment by olirice** [comment]
Queries use the same underlying SQL so we trust the postgres query optimizer to use indexes when it is appropriate (lots of data exists) and skip them when it's not. Since its not common knowledge that postgres may intentionally choose not to use an index (when it'll be slower) I'm leaning away from implementing this feature as it has the potential to confuse users
