### ISSUE TITLE
`create_index()` times out about 150k records.

### ISSUE THREAD

**Issue by dan-jacobson** [supabase/vecs#97]
**Describe the bug**
I built a collection with 168,761 rows and 384 dimensions. At the end of my table create, I called `my_collection.create_index()` and got:
`sqlalchemy.exc.OperationalError: (psycopg2.errors.QueryCanceled) canceling statement due to statement timeout`.

Tried again with `my_collection.create_index(vecs.IndexMethod.ivfflat)` and got the same thing.

**To Reproduce**
1. make a collection via `my_collection = vx.get_or_create_collection(name="my_collection", dimension=384)`
2. add a bunch of rows: my_collection.upsert(a_whole_bunch_of_data)
3. call `my_collection.create_index()`

**Expected behavior**
I expected to be able to create an index for 150k rows -- that's not too large, in my head. Or, I should be able to customize the timeout for index creation that I know will take a while.

**Versions:**
 - psycopg2-binary: Version: 2.9.9
 - vecs: Version: 0.4.4

**Additional context**
I have not tried downsampling to figure out exactly how many of my rows I can process before timing out, but I will try and update to include.

**Comment by olirice** [comment]
in this case i'd recommend using hnsw vs ivfflat. it performs better in almost all cases and can be built before data is inserted to avoid timeout issues
- create collection
- immediately create the hnsw index
- insert data

other options would be to go into your postgres instance and increase or disable the timeout for the relevant role (temporarily)
```sql
alter role your_role_name set statement_timeout = '10min';
```
(don't forget to put it back after)

it isn't an argument in vecs because we don't want to clobber any defaults put in place by your database admin
